application:
  name: Juth2-Server

server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

juth2:
  token:
    access-expire-time-in-sec: 1900
    refresh-expire-time-in-sec: 2100
  security:
    cookieEnabled: true
  allowed:
    methods: head